//get a random number between 1 and 3 inclusive.
//assign each number to Paper, Scissors or Rock.
//get a new random number (with associated word) each time
//that the function runs.

function getComputerChoice() {
    let compChoice = Math.floor(Math.random() * 3) + 1;
    switch (compChoice) {
        case 1: 
            return 'rock';
            break;
        case 2: 
            return 'paper';
            break;
        case 3: 
            return 'scissors';
            break;
    }
}

//prompt player for an input. 
//Transform the input to lowercase.
function getPlayerChoice() {
    let input = prompt('Rock, Paper or Scissors?').toLowerCase();
    return input;
}

//initialize a counter.
let counter;


//play a round of rock paper scissors by comparing the
//user input with the random input generated by the computer.
function playRound (playerSelection, computerSelection) {
    console.log(`player chose: ${playerSelection}. Computer chose: ${computerSelection}.`);

    if (playerSelection === computerSelection) {
        console.log('tie! no new points');
    } else if (computerSelection === 'rock') {
        if (playerSelection === 'paper') {
            console.log('You win! Paper beats rock.');
            return counter++;
        } else if (playerSelection === 'scissors') {
            console.log('You lose! Rock beats Scissors.')
            return counter--;
        }
    } else if (computerSelection === 'paper') {
        if (playerSelection === 'rock') {
            console.log('You lose! Paper beats rock.');
            return counter--;
        } else if (playerSelection === 'scissors') {
            console.log('You win! Scissors beat paper.');
            return counter++;
        }
    } else if (computerSelection === 'scissors') {
        if (playerSelection === 'rock')  {
            console.log('You win! Rock beats scissors.');
            return counter++;
        } else if (playerSelection === 'paper') {
            console.log('You lose! Scissors beat paper.');
            return counter--;
        }
    }
    //return counter;
}

//test args...
//const playerSelection = 'rock';
//const computerSelection = getComputerChoice();

//logging playround and computerSelection to the console to check if it works
//it does!
    //console.log(playRound(playerSelection, computerSelection));
    //console.log(computerSelection);
    //playRound(playerSelection, computerSelection);
    //playRound(getPlayerChoice(), getComputerChoice());


//playRound repeated 5 times. We also tally the score.
function game () {
    for (let i = 0; i < 5; i++) {
        playRound(getPlayerChoice(), getComputerChoice());
        //console.log(i);
        //console.log('computer choice: ' + getComputerChoice());
        console.log('counter: ' + counter);
    }
    //need to increment the counter here I think
}

game();

